---
title: "課堂練習模版"
author: "李少謹"
date: "2020-12-28"
output: output_format
params:
  id: "410773130"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
# Given some information
R <- 0.09
M <- 10000
T <- 3
# What I need to do
PDV <- 
{
  M/(1+R)**T
}
```

```{r}
getPDV <- function(R,M,T) 
{
  M/(1+R)**T
}
```


```{r}
getPDV(R=0.09, T=3, M=10000)
getPDV(0.09,10000,3)
```


```{r}
debug(getPDV) 
getPDV(R=0.09, T=3, M=10000) 
undebug(getPDV)
```


```{r}
# 查詢函數formals arguments要求
formals(getPDV)
```


```{r}
# 查詢函數主體
body(getPDV)

```


```{r}
# body執行時若有物件不存在execution environment時要去找尋的environment
environment(getPDV)
```


```{r}
# Given some information
T <- 3
# What I need to do
getPDV2 <- function(R,M){
  M/(1+R)**T
}
```


```{r}
getPDV2(R=0.12, M=50000)
debug(getPDV2)
getPDV2(R=0.12, M=50000)
undebug(getPDV2)
```


```{r}
T <- 3
getPDV2(R=0.12, M=50000)
```


```{r}
T <- 1
getPDV2(R=0.12, M=50000)
```


```{r}
globalX <- c(2,5)
testfun <- function(){
  globalX[[2]] <- -1
  invisible(3+globalX)
}
testfun()
globalX
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

