---
title: "課堂練習模版"
author: "李少謹"
date: "2020-12-01"
output: output_format
params:
  id: "410773130"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
example$name[c(T, F, T, F)]
```

```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
pick_above170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```
```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
```
```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```
```{r}
print(example[c("name","allowance")])
example$allowance
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```
```{r}
example$allowance <- 
  ordered(example$allowance)
example$allowance
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```

```{r}
print(example[c("name","bloodType")])

pick_bloodB <- example$bloodType == "B"
example$name[pick_bloodB]
```
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)

pick_evens <- (sequenceNums %% 2) == 0
sequenceNums[pick_evens]
```

```{r}
x <- c(1,5,8)
y <- c(5,8)

# x裡的元素值是不是屬於y集合
x %in% y
```
```{r}
print(example[c("name","residence")])

set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- example$residence %in% set_TaipeiMetro
example$name[pick_fromTaipeiMetro]
print(pick_fromTaipeiMetro)
```
```{r}
pick_not_fromTaipeiMetro <- ! pick_fromTaipeiMetro
# 或
pick_not_fromTaipeiMetro <- !(example$residence %in% set_TaipeiMetro) # (..) 裡面會先運算完才做外面!的處理
pick_not_fromTaipeiMetro
```
```{r}
print(example[c("name","residence")])

example$name[pick_fromTaipeiMetro]
example$name[pick_not_fromTaipeiMetro]
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```
```{r}
x2
is.na(x2)
is.na(x3)
```
```{r}
c(22,NA,18) -> a
a==NA
is.na(a)
```
```{r}
print(example[c("name","weight")])

pick_na <- is.na(example$weight)
pick_na
example$name[pick_na]
```
```{r}
0/0
```
```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")
pick_loveFood
example$name[pick_loveFood]
```

```{r}
pick_loveFood <- example$hobby == "美食"
pick_loveFood
```
```{r}
example[["hobby2"]] <- c("美食", "時尚", "美食", "旅遊")

print(example[c("name", "hobby2")])
pick_loveFood2 <- example$hobby2 == "美食"
example$name[pick_loveFood2]
```
```{r}
str(example)
pick_above170 <- example$height >= 170
pick_bloodB <- example$bloodType == "B"
pick_loveFood <- 
  stringr::str_detect(example$hobby,"美食")
pick_na <- is.na(example$weight)
pick_after98 <- 
  example$birthday >= lubridate::ymd("1998-01-01")
set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- 
  example$residence %in% set_TaipeiMetro
```
```{r}
str(example[c("name","hobby","bloodType")])
pick_loveFood & pick_bloodB
example$name[
    pick_loveFood & pick_bloodB
  ]
```
```{r}
example[c("name","birthday","residence")]
pick_after98 | !pick_fromTaipeiMetro
example$name[
  pick_after98 | !pick_fromTaipeiMetro
]
```

```{r}
example$name[pick_after98 & pick_fromTaipeiMetro & pick_bloodB]
```
```{r}
example$name[
  pick_after98 & pick_fromTaipeiMetro & pick_bloodB
]
```
```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-10","11-15"), 15, replace=T)
ages_chr
```

```{r}
unique(ages_chr)
```
```{r}
table(ages_chr)
```
```{r}
ages_fct1 <- 
  factor(
    ages_chr
  )
```
```{r}
table(ages_fct1)
table(ages_chr)
```
```{r}
ages_fct2 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-10","11-15")
  )
```
```{r}
table(ages_fct1)
table(ages_fct2)
```
```{r}
ages_fct2[[3]] #4以下
ages_fct2[[6]] #5-10
ages_fct2[[3]] > ages_fct2[[6]]
```
```{r}
ages_fct3 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-10","11-15"),
    ordered = T
  )
```

```{r}
ages_fct3[[3]] #4以下
ages_fct3[[6]] #5-10
ages_fct3[[3]] > ages_fct3[[6]]
ages_fct3[[6]] < "11-15" # 也可以用文字寫下levels中有的分類
```
```{r}
# 忘了告訴電腦是ordered factor
ages_fct2_order = factor(ages_fct2, ordered=T)
ages_fct2_order
# 也可以
ages_fct2_order = as.ordered(ages_fct2)
ages_fct2_order
# 忘了告訴電腦呈現順序是"11-15","5-10","4以下"
ages_fct3_newLevels = 
  factor(
    ages_fct3, 
    levels = c("11-15","5-10","4以下")
  )
ages_fct3_newLevels
is.ordered(ages_fct3_newLevels)
ages_fct3_newLevels
```
```{r}
try <- factor(c(1,2,3,2,1),levels = c(1,2,3),ordered = T)
class(try)
as.data.frame(try)
```
```{r}
library(stringr)
fruit <- c("apple", "banana", "pear", "pinapple")
str_detect(fruit, "a")
str_detect(fruit, "^a")
str_detect(fruit, "a$")
str_detect(fruit, "b")
str_detect(fruit, "[aeiou]")

# Also vectorised over pattern
str_detect("aecfg", letters)

# Returns TRUE if the pattern do NOT match
str_detect(fruit, "^p", negate = TRUE)
```

```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
sum(logi1)
```

```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)

pick_evens <- (sequenceNums %% 2) == 0
pick_evens
sequenceNums[pick_evens]
```

```{r}
student1 <-
  list(
    name = character(),
    id = character(),
    gmail = character(),
    googleClassroom =
      list(
        displayName = character()
      ),
    github =
      list(
        username = character(),
        repoUrl = character()
      ),
    homeworks = list(),
    exams = list(),
    list()
  )

names(student1) # 每個元素名稱
length(student1) # 元素個數
```


























































































































