---
title: "課堂練習模版"
author: "李少謹"
date: "2020-12-12"
output: output_format
params:
  id: "410773130"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code








```{r}
library(purrr)
```

```{r}
sukiyaMenu <- jsonlite::fromJSON("https://www.dropbox.com/s/iu9b1hnvbtss83q/sukiyaMenu.json?dl=1")

nonsetMenu3 <- sukiyaMenu[c("豪華雙饗丼", "牛丼類", "咖哩類" )]
```



```{r}
items <- list()
items$dish_name = vector("list", length=3)
```


```{r}
items$dish_name
```


```{r}
charVect <- vector("character", 5)
charVect
charVect <- vector()

```


```{r}
# 餐點名稱
dish_name = nonsetMenu3[[1]]$name
items$dish_name[[1]] <- unlist(dish_name)

dish_name = nonsetMenu3[[2]]$name
items$dish_name[[2]] <- unlist(dish_name)

dish_name = nonsetMenu3[[3]]$name
items$dish_name[[3]] <- unlist(dish_name)

items
```


```{r}
nonsetMenu3$豪華雙饗丼$name
dish_name
class(dish_name)
unlist(dish_name)
```


```{r}
# 餐點名稱
{
  dish_name <- nonsetMenu3[[1]]$name
  items$dish_name[[1]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[2]]$name
  items$dish_name[[2]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[3]]$name
  items$dish_name[[3]] <- unlist(dish_name)
}
```


```{r}
{
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  items$dish_name[[1]] <- unlist(dish_name)  # 2nd expression
} ->result
items$dish_name[[1]]  # 或
unlist(dish_name)
result
```


```{r}
result4 <- {
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  cat(unlist(dish_name))  # 2nd expression
}
result4
```


```{r}
mingsPrice <- # 找出小明價格
{
  sizeChoice <- nonsetMenu3[["豪華雙饗丼"]][["product_variations"]][[2]]
  pick_size <- sizeChoice$name == '飯大碗'
  sizeChoice$price[pick_size]
}

yingsPrice <- # 找出小英價格
{
  sizeChoice <- nonsetMenu3[["牛丼類"]][["product_variations"]][[4]]
  pick_size <- sizeChoice$name == '迷你碗'
  sizeChoice$price[pick_size]
}

total= mingsPrice + yingsPrice
total
View(nonsetMenu3)
sizeChoice$name
pick_size
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

