---
title: "課堂練習模版"
author: "李少謹"
date: "2020-10-28"
output: output_format
params:
  id: "410773130"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vectorExample <- c("小李","小少","小謹")
vectorExample[[1]]
```



```{r}
vectorExampleWithName[c("p1","p3")]
```
```{r}
vectorExampleWithName[c(T,F,T)]
vectorExampleWithName[c(TRUE,FALSE,T)]
```





```{r}
pickByNumber <- c(1,3)
pickByName <- c("p1","p3")
c(T,F,T) -> pickByLogical
```

```{r}
vectorExampleWithName[pickByLogical]
vectorExampleWithName[pickByName]
vectorExampleWithName[pickByNumber]
```



```{r}
str(listExample,1)
```
```{r}
listExample[c(1,2)]
listExample[c("student","學期")]
listExample[c(T,T)]
```


```{r}
vectorExampleWithName <- c("p1"="小李","p2"="小少","p3"="小謹")
vectorExampleWithName[[1]]
vectorExampleWithName[["p1"]]
vectorExampleWithName[c("p1","p3")]
vectorExampleWithName[c("1","p3")]

```



```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
```

```{r}
weather[[1]][[2]][[2]]  # 今天/新北市/highest_temp
weather[[2]][[2]][[2]]  # 明天/新北市/highest_temp
```

```{r}
weather$today$highest_temp  # 今天/新北市/highest_temp
weather$highest_temp  # 明天/新北市/highest_temp

```

```{r}
vectorExample <- c("小明", "小英", "大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
listExample
```

```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
studentName <- c("小英", "小美", "大雄", "阿華", "阿尼")
gender <- c("F", "F", "M", "F", "M")
```

```{r}
majors
```

```{r}
pickEcon <- c(T,T,F,F,T)
studentName[pickEcon]
gender[pickEcon]
```

```{r}
pickEcon <- majors == "經濟學系"
studentName[pickEcon]
gender[pickEcon]
```

```{r}
which(pickEcon)
```


```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
```



```{r}
weather[[1]][[2]][[2]]  # 今天/新北市/highest_temp
weather[[2]][[2]][[2]]  # 明天/新北市/highest_temp
```
```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp  # 明天/新北市/highest_temp
```


















