---
title: "課堂練習模版"
author: "李少謹"
date: "2020-11-24"
output: output_format
params:
  id: "410773130"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)
```
##extra 1 element
```{r}
AA[[1]]
AA[1] 
```
```{r}
str(LL)
```

```{r}
str(LL[[1]])
str(LL[1])
```

```{r}
a <- c(2, 5, 7)
a[[4]]
```

```{r}
a[[4]] <- 8
print(a)
```


```{r}
restaurant = "すき家 Sukiya (新北三峽店)"
date = lubridate::mdy("Nov 10, 2020")
order = list(
  list(
    item="蕃茄牛丼",
    quantity=1
  ) # 這裡少了一筆 "起司蕃茄牛丼"
)
total = 328
```

```{r}
oneOrder <- list(
  "restaurant"=restaurant,
  "date"=date,
  "order"=order,
  "total"=total
)
str(oneOrder)
```
```{r}
oneOrder$order[[2]]
```
```{r}
oneOrder$order[[2]] <- list(
    item="起司蕃茄牛丼",
    quantity=1
  )
```

```{r}
str(oneOrder)
```

```{r}
a <- c(2, 5, 7)
a[c(4,5)]
```

```{r}
a[c(4,5)] <- c(8,12)
print(a)
```

```{r}
print(a)
```


```{r}
length(oneOrder$order)
blue3 <- list(
  item="牛丼飯",
  quantity=1
) 
blue4 <- oneOrder$order[[1]]
blue4$item <- "豬排飯"
blue4$quantity <- 1



```

```{r}
oneOrder$order[c(3,4)] <- list(blue3,blue4)
```

```{r}
str(oneOrder)
```

```{r}
# 取出目前已有的子元素一個當模版
secondItem <- oneItem <- oneOrder$order[[1]]

oneItem$item <- "牛丼飯"
oneItem$quantity <- 1
secondItem$item <- "豬排飯"
secondItem$quantity <- 1

oneOrder$order[newOrders] <- list(
  oneItem, secondItem
)
```

```{r}
oneOrder$order[
  newOrderSeq
] <- 
  list(
    list(
      item="牛丼飯",
      quantity=1
    ),
    list(
      item="豬排飯",
      quantity=1
    )
  )

View(oneOrder)
```

```{r}
secondItem <- oneItem <- oneOrder$order[[1]]
oneItem$item <- "牛丼飯"
oneItem$quantity <- 1
str(oneItem)
```

```{r}
library(lubridate)
 LL0 <- LL <- list(
  "Mary was born on", 
  ymd("1995-7-1"),
  "John was born on",
  ymd("1997-10-27")
  )
LL[[2]] <- ymd("1995-7-8")
print(LL)
```

```{r}
oneOrder$order[[1]]$quantity
```
```{r}
oneOrder$order[[1]]$quantity <- 2
```

```{r}
View(oneOrder)
```
```{r}
LL[c(2,4)]
LL[c(2,4)] <- 
  list(
    ymd("1995-7-8"),
    ymd("1997-10-17")
  )
LL <- LL0
print(LL0)
print(LL[c(2,4)])
```

```{r}
anotherOrder <- 
  list(
    restaurant="古橋飲食店",
    date=lubridate::mdy("Nov 9, 2020"),
    order=list(
      list(
        item="古早味排骨飯",
        quantity=1
      )
    ),
    total=89
  )
thirdOrder <-
  list(
    restaurant="Tijo Kitchen",
    date=lubridate::mdy("Nov 8, 2020"),
    order=list(
      list(
        item="韓式泡菜黑咖哩飯",
        quantity=1
      )
    )
  )
```

```{r}
allMyOrders0 <- allMyOrders <-  # allMyOrder0等一下還原用
  list(
    oneOrder
  )
```

```{r}
allMyOrders[[2]] <- anotherOrder
allMyOrders[[3]] <- thirdOrder

str(allMyOrders)
```
```{r}
allMyOrders <- allMyOrders0
allMyOrders[c(2,3)] <- list(
  anotherOrder,
  thirdOrder
)
str(allMyOrders)
```

```{r}
View(allMyOrders)
allMyOrders[[3]]$total <- 160
```


```{r}

```













































































