---
title: "課堂練習模版"
author: "李少謹"
date: "2021-01-13"
output: output_format
params:
  id: "410773130"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
testFun <- function(){
  a <-2
  b <- 5
  return(a+b)
}
testFun()
```


```{r}
testErrorFun <- function(){
  a <-2
  b <- 5
  output <- a+b
}
testErrorFun()
```


```{r}
set.seed(10739)
customers <- data.frame(
  bills = sample(200:500, 10),
  vouchers = sample(c(T,F), size=10, replace=T,
                     prob=c(0.4,0.6)
                     )
)
head(customers)
```


```{r}
bill <- customers$bills[[3]]
hasVoucher <- customers$vouchers[[3]]
totalBill <- 
{
  startingBill <- bill
  if(hasVoucher)
  {
    bill <- bill - 20
  }
  message("You initial bill is ", startingBill,".\n",
          "You final bill is ", bill)
  bill
}
print(totalBill)
```


```{r}
get_totalBill <- function(bill, hasVoucher)
{
  startingBill <- bill
  if(hasVoucher)
  {
    bill <- bill - 20
  }
  message("You initial bill is ", startingBill,".\n",
          "You final bill is ", bill, "\n")
  bill
}
```


```{r}
purrr::map2(
  customers$bills, customers$vouchers,
  ~get_totalBill(.x, .y)
)
```


```{r}
f <- function(x){
  if(x<0)
  {
    stop("x has to be non-negative.")
  }
  sqrt(x)
}
```


```{r}
f(-2)
f(2)
```


```{r}
comment_grade <- function(grade){
  if(grade < 60) return("Don't give up. There is still hope.")
  return("Good job. Keep going")
}
comment_grade(59)
```


```{r}
df_grades <- data.frame(
  grade=sample(50:95, 20, replace = T)
)
purrr::map_chr(
  df_grades$grade,
  comment_grade
) -> df_grades$comment
```


```{r}
grades <- c(55, 72, 40) # fail in first
# any one failed? 
if(grades < 60) message("\nYes, someone failed")
```


```{r}
grades <- c(72, 55, 40) # fail in second
# any one failed? 
if(grades < 60) message("\nYes, someone failed")
```


```{r}
grades <- c(72, 55, 82)
# any one failed? 
if(any(grades < 60)) message("\nYes, someone failed")
```


```{r}
grades <- c(72, 55, 82)
# any one failed? 
if(any(grades < 60)) message("\nYes, someone failed")
```


```{r}
grade1 <- list(
  economics=55,
  calculus=77
)
grade2 <- c(
  economics=55,
  calculus=77
)
```


```{r}
(is.list(grade1) &  grade1$economics > 60)
(is.list(grade2) &  grade2$economics > 60)
```


```{r}
(is.list(grade1) && grade1$economics > 60)
(is.list(grade2) && grade2$economics > 60)
```


```{r}
myAge <- 75

if(myAge >=65 | stop("Error")){
  "Qualified"
} else {
  warning("Not qualified")
}
```


```{r}
if(myAge >=65 ||  stop("Error")){
  "Qualified"
} else {
  warning("Not qualified")
}
```


```{r}
# 前提條件
x <- 4L
# 任務
fx <- {
  
  # ending scenario 1:
  if(x %% 2 ==0)
  {
    x/2
  } else
  # ending scenario 2:
  {
    -(x+1)/2
  }
}

fx
```


```{r}
fx <- function(x)
{
  # ending scenario 1:
  if(x %% 2 ==0)
  {
    return(x/2)
  } else
  # ending scenario 2:
  {
    return(-(x+1)/2)
  }
}
```


```{r}
fx(4L)
fx(7L)
```


```{r}
sortedEmails <- list(
  office=character(),
  student=character(),
  private=character()
)
```


```{r}
set.seed(2839)
emailFrom <- sample(
  c("econ@gm.ntpu.edu.tw","classStudents@gm.ntpu.edu.tw","xxx@gmail.com","econStaff@gm.ntpu.edu.tw","yyyy@gmail.com"), 50,
  replace=T
)
head(emailFrom, 10)
```


```{r}
.x<- 3
commingEmail <- emailFrom[[.x]]
```


```{r}
# Office
{
  message("You have a message from office.")
  nOffice <- length(sortedEmails$office)
  sortedEmails$office[[nOffice+1]] <- commingEmail
  sortedEmails
}
# Student
{
  message("There is an email from student in your class.")
  nStudent <- length(sortedEmails$student)
  sortedEmails$student[[nStudent+1]] <- commingEmail
  sortedEmails
}
# Private
{
  message("A private message has come in.")
  nPrivate <- length(sortedEmails$private)
  sortedEmails$private[[nPrivate+1]] <- commingEmail
  sortedEmails
}
```


```{r}
condition_sgn <- 
  ifelse(
    str_detect(commingEmail,"econ"), "office", commingEmail)
```


```{r}
switch(
  condition_sgn,
  "office"={
    message("You have a message from office.")
    nOffice <- length(sortedEmails$office)
    sortedEmails$office[[nOffice+1]] <- commingEmail
    sortedEmails
  },
  "classStudents@gm.ntpu.edu.tw"={
    message("There is an email from student in your class.")
    nStudent <- length(sortedEmails$student)
    sortedEmails$student[[nStudent+1]] <- commingEmail
    sortedEmails
  },
  {
    message("A private message has come in.")
    nPrivate <- length(sortedEmails$private)
    sortedEmails$private[[nPrivate+1]] <- commingEmail
    sortedEmails
  }
)
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

